### ISSUE TITLE
superfluous  code

### ISSUE THREAD

**Issue by zhangtianxiao** [wangzihaogithub/spring-boot-protocol#18]
`ServletHttpServletRequest#newSessionId`,  SNOWFLAKE_ID_WORKER always execute.

**Comment by wangzihaogithub** [comment]
确实 , 刚提交了代码. 解决了一下,你看看. 
实如果你想写的话, 可以提pull request. 我把你加到项目里来

https://github.com/wangzihaogithub/spring-boot-protocol/commit/ede7ed764df18d7e7ce2f4ce2ded1727ddbb57e3
