### ISSUE TITLE
http服务返回null 或者 http对象,如下:

### ISSUE THREAD

**Issue by Wilfred-Aha** [wangzihaogithub/spring-boot-protocol#2]
![image](https://user-images.githubusercontent.com/44184276/68927831-a23ac880-07c3-11ea-9b5f-a1ba7befe967.png)

这两种结果的,前台是收不到请求,能实现的到吗?

**Comment by wangzihaogithub** [comment]
可以 今天会提交一波

**Comment by Wilfred-Aha** [comment]
哈哈,谢谢 你有时间补充下

**Comment by wangzihaogithub** [comment]
![image](https://user-images.githubusercontent.com/18204507/68937010-97d5fa00-07d6-11ea-8dff-396e75b8b914.png)

![image](https://user-images.githubusercontent.com/18204507/68937030-a45a5280-07d6-11ea-8a22-2d4e5634b5a3.png)

我已经改过这个, 从master分支拉一下代码, install到本地, 用2.0.4版本是好的.

这个原因是需要给netty写入 LastHttpContent类,以确认本次http请求结束后. 才会把Channel状态改为等待下一次请求.

**Comment by Wilfred-Aha** [comment]
可以提下代码吗

**Comment by wangzihaogithub** [comment]
这个现在在好使的, 不用改代码. 你install一下, maven中使用2.0.4版本 就好了

**Comment by Wilfred-Aha** [comment]
可能是我maven问题,下载2.0.4的下不下来,2.0.0的是可以下载的

**Comment by Wilfred-Aha** [comment]
你是指现在spring-boot-protocol已经是2.0.4版本了吗?
![image](https://user-images.githubusercontent.com/44184276/68944022-be506100-07e7-11ea-8d4f-02bda14c3ff5.png)

**Comment by Wilfred-Aha** [comment]
我如果下载maven仓库里面的2.0.4好像下载不成功,之前的2.0.0的是能下载成功的.

**Comment by wangzihaogithub** [comment]
目前正在上传maven中央仓库的过程中,你应该还下载不了.   需要你手工编译源码安装(install) 才能引用.

**Comment by Wilfred-Aha** [comment]
我现在引入的本地的2.0.4版本,就是现在spring-boot-protocol,但是还是存在这个问题哦
![image](https://user-images.githubusercontent.com/44184276/68944532-015f0400-07e9-11ea-8a07-22fe60c5c7d8.png)

**Comment by wangzihaogithub** [comment]
前台收不到响应的症状是什么样子,  截个图看看, F12打开调试看下接口返回

**Comment by Wilfred-Aha** [comment]
就比如test02 和 test03这两个接口:
![image](https://user-images.githubusercontent.com/44184276/68945025-56e7e080-07ea-11ea-9174-48da4942e64f.png)

![image](https://user-images.githubusercontent.com/44184276/68945000-4a638800-07ea-11ea-8842-9426f1fc4be0.png)

我使用postman,进行访问的话,前台获取不到响应

**Comment by Wilfred-Aha** [comment]
如果直接去掉@EnableNettyEmbedded注解,使用tomcat的话,前台是能够收到响应的,如下:
test03接口:
![image](https://user-images.githubusercontent.com/44184276/68945363-32d8cf00-07eb-11ea-9e98-5d85f944a799.png)
test02接口:

![image](https://user-images.githubusercontent.com/44184276/68945332-22285900-07eb-11ea-87fc-1f9cee9796b7.png)

**Comment by Wilfred-Aha** [comment]
不知道我描述的清不清楚,我加了你qq好友,有时间的话交流下,

**Comment by wangzihaogithub** [comment]
![springboot-protocol总览](https://user-images.githubusercontent.com/18204507/68989252-9d871a80-087e-11ea-96e1-20c12689c12a.png)
大概先画了个图, 等会在readme里补上文字

**Comment by Wilfred-Aha** [comment]
#1 这个问题好像还是存在,我现在使用的是最新版本的2.0.4

**Comment by wangzihaogithub** [comment]
QQ上让我远程操作一下, 看一下你那的情况

**Comment by Wilfred-Aha** [comment]
现在在上班,远程的话不方便,我晚上回去让你操作下

**Comment by wangzihaogithub** [comment]
好

**Comment by Wilfred-Aha** [comment]
大致上我描述了下,截图发你qq了

**Comment by wangzihaogithub** [comment]
https://github.com/wangzihaogithub/spring-boot-protocol/commit/5d65efbd344de5f7bf0bbf26f41194af401032d5#diff-5cc0fd4f3030dd569c36b8c4d6d5ff04

已解决.请使用2.0.5版本
