### ISSUE TITLE
当websocket与spring整合, 不能摆脱对tomcat的依赖吗

### ISSUE THREAD

**Issue by zhangtianxiao** [wangzihaogithub/spring-boot-protocol#20]
详见org.springframework.web.socket.server.support.AbstractHandshakeHandler#initRequestUpgradeStrategy,
当我排除spring-boot-starter-web对tomcat-starter的依赖, websocket便无法成功适配

**Comment by zhangtianxiao** [comment]
> 详见org.springframework.web.socket.server.support.AbstractHandshakeHandler#initRequestUpgradeStrategy, 当我排除spring-boot-starter-web对tomcat-starter的依赖, websocket便无法成功适配

问题已解决, 在registerWebSocketHandlers中.setHandshakeHandler(new HandshakeHandlerX())即可

**Comment by wangzihaogithub** [comment]
确实 你那样也能实现. 我加了个tomcat类, 改成了不需要那样也行. 
  
https://github.com/wangzihaogithub/spring-boot-protocol/commit/e2e0893d4539016dc2a443a9b13e38a269bf303b
