### ISSUE TITLE
关于线程池，大佬求解答。。

### ISSUE THREAD

**Issue by fzdwx** [wangzihaogithub/spring-boot-protocol#22]
你好，为什么说用了线程池来执行`http runnable`比只用`event loop` 的qps 高？

我以为,把`http runnable`提交到线程池就是直接返回了，然后继续提交下一个`http runnable`，应该更高？

**Comment by wangzihaogithub** [comment]
如果有阻塞代码的话, 用线程池qps高. 
如果没阻塞代码的话, 在 netty的 eventloop 里执行qps高. 

因为增加qps的核心体现在快速把数据写到网卡 与 快速从网卡读到请求. 

spring-boot-protoco对这两种方式都支持.

建议如果要高性能代码的话, 可以把阻塞数据写内存, 然后批量持久化, 如果要保证事物可以用WAL. 这样QPS就非常高了,可以达到每秒几万

**Comment by wangzihaogithub** [comment]
提交http runnable不是本质, 本质是 http runnable过程中会把数据写到网卡,  runnable不切换线程, 直接写网卡效率更高

**Comment by fzdwx** [comment]
> 提交http runnable不是本质, 本质是 http runnable过程中会把数据写到网卡, runnable不切换线程, 直接写网卡效率更高

感觉解答，有概念了！
