### ISSUE TITLE
websocket无法使用

### ISSUE THREAD

**Issue by WenjieYin** [wangzihaogithub/spring-boot-protocol#28]
Hi, Zihao。在试用websocket功能的时候，直接运行https://github.com/wangzihaogithub/spring-netty-example/tree/master/netty-example-websocket-server，
发现客户端连接websocket服务端的时候，一直处于pending的状态，无法连接成功。
![demo运行界面](https://github.com/wangzihaogithub/spring-boot-protocol/assets/57325233/ae585e43-9939-4b5c-abd5-2e80cc166aa4)
![浏览器](https://github.com/wangzihaogithub/spring-boot-protocol/assets/57325233/55f6699e-2168-45a1-8324-b5c973d826da)

**Comment by wangzihaogithub** [comment]
升级2.3.12试下呢

**Comment by WenjieYin** [comment]
> Hi, Zihao。在试用websocket功能的时候，直接运行[https://github.com/wangzihaogithub/spring-netty-example/tree/master/netty-example-websocket-server，](https://github.com/wangzihaogithub/spring-netty-example/tree/master/netty-example-websocket-server%EF%BC%8C) 发现客户端连接websocket服务端的时候，一直处于pending的状态，无法连接成功。 ![demo运行界面](https://private-user-images.githubusercontent.com/57325233/293501521-ae585e43-9939-4b5c-abd5-2e80cc166aa4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyMDY4MzUsIm5iZiI6MTcwNDIwNjUzNSwicGF0aCI6Ii81NzMyNTIzMy8yOTM1MDE1MjEtYWU1ODVlNDMtOTkzOS00YjVjLWFiZDUtMmU4MGNjMTY2YWE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAyVDE0NDIxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlMjBmOWUyNmQyYWNhNDNjZjk5MDgxZmMwNmE4MmE2YjZmNDAyOWU2MmI5ZjhlZmE1NWE1M2ZlN2ZiZDIyYjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wXCF23f06SlY3G3KbuRT2c3bw5WN0DKRdYIpcrL_Ofc) ![浏览器](https://private-user-images.githubusercontent.com/57325233/293501522-55f6699e-2168-45a1-8324-b5c973d826da.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyMDY4MzUsIm5iZiI6MTcwNDIwNjUzNSwicGF0aCI6Ii81NzMyNTIzMy8yOTM1MDE1MjItNTVmNjY5OWUtMjE2OC00NWExLTgzMjQtYjVjOTczZDgyNmRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAyVDE0NDIxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1MmM4OGNjMDYwZWY1NTNlZTU3MWYyZWIwZjQ4MDM4ZmU3OTQyNjdlZTA5M2IyODdjOTZiMjY5MmM2NmE2MzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VcCiYVrgGetDqxet8UGjmxGfTGm59ENHygxArC-36pc)

问题在2.3.13版本已解决
