### ISSUE TITLE
对src/main/resources下文件支持有些问题

### ISSUE THREAD

**Issue by WenTao-Love** [wangzihaogithub/spring-boot-protocol#37]
![image](https://github.com/wangzihaogithub/spring-boot-protocol/assets/7439225/b57be2e7-8e87-4915-8b5a-664e3232c446)
![image](https://github.com/wangzihaogithub/spring-boot-protocol/assets/7439225/074d1188-96ad-4e59-b663-a80a7cda70fd)
组件依赖：
spring-boot-protocol 2.3.18
beetlsql 3.30.9-RELEASE
`

<dependency>
    <groupId>com.ibeetl</groupId>
    <artifactId>sql-springboot-starter</artifactId>
    <version>3.30.9-RELEASE</version>
</dependency>
`
beetlsql3在spring-boot-tomcat环境下运行正常，切换到spring-boot-protocol就报找不到md文件。
我在target/classes/sql 文件夹下是可以找到这些相关文件的！

**Comment by WenTao-Love** [comment]
https://mvnrepository.com/artifact/com.ibeetl/sql-springboot-starter/3.30.9-RELEASE

**Comment by wangzihaogithub** [comment]
我试下

**Comment by wangzihaogithub** [comment]
找到问题了，晚上发布2.3.19

**Comment by WenTao-Love** [comment]
感谢，可以顺道优化一个Pom.xml吗？谢谢

**Comment by wangzihaogithub** [comment]
已发布2.3.19解决了
