### ISSUE TITLE
springboot创建websocket客户端报错

### ISSUE THREAD

**Issue by yx-overzero** [wangzihaogithub/spring-boot-protocol#44]
public void connect(String url) {
      StandardWebSocketClient client = new StandardWebSocketClient();
      this.connectionManager = new WebSocketConnectionManager(client, this.webSocketClientHandler, url);
      this.connectionManager.start();
  }

当如此创建websocket客户端去连websocket接口时，我使用了如下

public class ContainerProviderImpl extends ContainerProvider {
    @Override
    protected WebSocketContainer getContainer() {
        return new WebSocketServerContainer();
    }
}

但WebSocketServerContainer未实现connectToServer接口，未能成功接发消息

**Comment by wangzihaogithub** [comment]
是因为我并没实现websocket的connectToServer接口。
因为我觉得大家用websocket客户端时，往往会用第三方库。

> public void connect(String url) { StandardWebSocketClient client = new StandardWebSocketClient(); this.connectionManager = new WebSocketConnectionManager(client, this.webSocketClientHandler, url); this.connectionManager.start(); }
> 
> 当如此创建websocket客户端去连websocket接口时，我使用了如下
> 
> public class ContainerProviderImpl extends ContainerProvider { @OverRide protected WebSocketContainer getContainer() { return new WebSocketServerContainer(); } }
> 
> 但WebSocketServerContainer未实现connectToServer接口，未能成功接发消息

**Comment by wangzihaogithub** [comment]
了解一下为什么选择用servlet的websocket客户端呢？ 是因为想减少项目依赖吗？

**Comment by yx-overzero** [comment]
祖传代码，这个没有计划的话，我试试其他方式，感谢大佬
