### ISSUE TITLE
导入了过期的包

### ISSUE THREAD

**Issue by luanweijie** [wangzihaogithub/spring-boot-protocol#7]
https://github.com/wangzihaogithub/spring-boot-protocol/blob/master/src/main/java/com/github/netty/core/AbstractNettyServer.java#L4

包import io.netty.bootstrap.ChannelFactory;
已经过期
正确的应该是 import io.netty.channel.ChannelFactory;

**Comment by wangzihaogithub** [comment]
这个是为了同时兼容 netty3，netty4 ，netty5， 
你看到其他用反射调用的代码， 也是为了兼容。

因为当用户导入包的时候， 会以用户导入的包为准。

**Comment by wangzihaogithub** [comment]
很细心呀 棒！
spring自动配置那块也是， 为了同时兼容，springboot2.0, 2.1, 2.2

**Comment by luanweijie** [comment]
阿西吧，666
