### ISSUE TITLE
 Size of HttpObjectAggregator maxContentLength is 0, response 413 for all http requests

### ISSUE THREAD

**Issue by markbanyang** [wangzihaogithub/spring-boot-protocol#9]
HttpServletProtocolSpringAdapter中根据multipart大小设置HttpObjectAggregator的maxContentLength，当文件大小限制超过2G,由于强制转换导致HttpObjectAggregator的maxContentLength值被设置为0。

**Comment by wangzihaogithub** [comment]
我看下,稍等10分钟

**Comment by wangzihaogithub** [comment]
netty的请求聚合最大支持2G, 因为它的构造方法就是int类型, 

等我改成不用netty聚合的后, 就发布2.0.16版本. 估计这几天就可以发布到maven中央仓库里

**Comment by markbanyang** [comment]
好的

**Comment by wangzihaogithub** [comment]
额 还没弄完, 这个是临时先提交的, 完了会明确告诉你的.

**Comment by markbanyang** [comment]
明白了 感谢

**Comment by wangzihaogithub** [comment]
在2.0.17版本改好了,  已经将master分支上传到maven仓库了,  应该明天就能在中央仓库拉到2.0.17版本的了.

**Comment by wangzihaogithub** [comment]
这样配置

spring:
  servlet:
    multipart:
      #请求头的上限
      max-request-size: 10GB
      #请求体的上限
      max-file-size: 10GB
      #超过多少大小，就把请求体放在文件存储。
      file-size-threshold: 2MB

**Comment by markbanyang** [comment]
好的

**Comment by markbanyang** [comment]
在NettyMessageToServletRunnable里面先处理HttpRequest，HttpContent。当msg是DefaultFullHttpRequest时会被忽略掉HttpConetnt导致不能正常处理请求
![image](https://user-images.githubusercontent.com/48742762/100176600-9243e180-2f0b-11eb-9717-834b480150b7.png)
